export const NEURAL_STATUS_MESSAGES = [
  'ANALISANDO PADRÕES VOCAIS...',
  'MAPEANDO SINAPSES SUBCOGNITIVAS...',
  'DETECTANDO DISSONÂNCIA COGNITIVA...',
  'CALIBRANDO SENSORES ACÚSTICOS...',
  'SINCRONIZANDO BIO-FEEDBACK...',
  'DECODIFICANDO CAMADAS EMOCIONAIS...',
  'RASTREAMENTO DE BLOQUEIOS ATIVO...',
  'ISOLANDO RUÍDO PSICOSSOMÁTICO...',
];
